### PR TITLE
Link Prediction Plugin

### PR DESCRIPTION
**Pull request by romanutti**
Link-prediction plugin for gephi, to predict future edges using different algorithms.

The following functionalities are supported:
- Creation of new edges through link prediction
- Filtering of those created edges per algorithm
- Evaluate quality of link prediction algorithms

The functionality of the plugin and the algorithms are described in detail in the README.

### CODE REVIEW

**Comment by mbastian** [comment]
Hi @romanutti and thanks for the submission. Impressive addition! I made the following changes:
- Removed `link-prediction.log` file
- Removed Log4j and replaced with the Logger we use for the rest of Gephi. We prefer not to add any extra logging library.
- Adapted the tests to JUnit4 using the default JUnit we use for the rest of Gephi. Makes dependencies cleaner with minimal code differences.
- Removed the `@Ignore` annotation on `PreferentialAttachmentStatisticsTest`
- Removed *.iml files as we don't want IDE-specific files
- Made some minor optimisations removing unnecessary data structures creations
- Corrected how the filter panel is setting the property back to the filter -> this is important to make sure the UI updates accordingly
- Wrap the write lock into try/finally to make sure it gets unlocked in case of errors
- Wrapped the message dialog into `SwingUtilities.invokeLater()` so it runs on the proper Swing thread (as opposed to the filter thread)
- Removed the GEXF files in `resources` as they were not used

Let me know what you think, otherwise I don't see other immediate issues but I'll have a second lonk

**Comment by mbastian** [comment]
@romanutti Ping!

**Comment by romanutti** [comment]
> 

Thanks a lot for wrapping that up! Quickly went through it - looks fine from my perspective :) Should we git it a go?

**Comment by romanutti** [comment]
> 

Thanks a lot for wrapping that up! Quickly went through it - looks fine from my perspective :) Should we git it a go?

**Comment by mbastian** [comment]
Thanks! I've merged it and the plugin is now published: https://gephi.org/plugins/#/plugin/link-prediction

It's a great addition to Gephi!

Also, note that I've created a [link-prediction-plugin](https://github.com/gephi/gephi-plugins/tree/link-prediction-plugin) branch in this repository. If you want you can directly make changes there and then do PRs against `master-forge`. I think it's easier than working on a fork but it's your call. 

One minor is the "Invalid equation" error one can see on the README: https://gephi.org/plugins/#/plugin/link-prediction

**Comment by romanutti** [comment]
> Thanks! I've merged it and the plugin is now published: https://gephi.org/plugins/#/plugin/link-prediction
> 
> It's a great addition to Gephi!
> 
> Also, note that I've created a [link-prediction-plugin](https://github.com/gephi/gephi-plugins/tree/link-prediction-plugin) branch in this repository. If you want you can directly make changes there and then do PRs against `master-forge`. I think it's easier than working on a fork but it's your call.
> 
> One minor is the "Invalid equation" error one can see on the README: https://gephi.org/plugins/#/plugin/link-prediction

Working at the branch will probably be easier. 

And will also check the issue with the equations in the README.md 👍🏼

**Pull request merged**
