### PR TITLE
Add HTTP Graph for Gephi 0.9

### PR DESCRIPTION
**Pull request by phreakocious**
Now works with 0.9.  Also new support added for receiving data from a separate Chrome extension.

### CODE REVIEW

**Comment by eduramiba** [comment]
Thanks for the request! I will check this soon.

**Comment by phreakocious** [comment]
Could this get looked at soon, please?

**Comment by eduramiba** [comment]
Maybe I can check this later today

**Comment by eduramiba** [comment]
Looks good to me! Only problem is you should remove `<version>0.9.1</version>` from your module pom.xml dependencies to `lib.validation` and `io-importer-api`. This is not necessary because dependency versions are managed by parent pom.

Please do this so I can marge.

**Comment by phreakocious** [comment]
Thanks, @eduramiba .. Done.

**Comment by eduramiba** [comment]
Your plugin is now available in the update center :smiley:

**Pull request merged**
