### PR TITLE
Implementation of Leiden algorithm

### PR DESCRIPTION
**Pull request by vtraag**
This plugin provides an implementation of the Leiden algorithm (based on https://github.com/CWTSLeiden/networkanalysis) for community detection, see that repository for more details. It is quite complete as is, I believe, including several configuration options. More information about each option is provided in tooltips.

There are some specific points you may wish to check:

1. Are graphs with multiple edges handled correctly? I believe they are, but you may want to double check this. I am not entirely sure if this is also the case for dynamical/temporal graphs.
2. I am not that familiar with maven, so perhaps some of the configuration in the pom.xml is not entirely correct. Please let me know if anything needs to be changed.
3. I am not sure whether the `RunClusteringBuilder` is actually required? I simply included this because it was also used by for the modularity plugin.

As requested in `README.md` I now created the pull-request with `master-forge` branch as the base, but it cannot merge automatically (I did merge upstream changes). If it should be merged with the `master` branch instead, let me know.

The current implementation simply relies on a copy of the source code at https://github.com/CWTSLeiden/networkanalysis, since the package is not yet in maven. Whenever it becomes available through maven, it should simply be declared a dependency, since no adaptation of the code is required.

### CODE REVIEW

**Comment by eduramiba** [comment]
Hi Vicent,
This is awesome, thanks for the quick implementation!! I will review the plugin as soon as possible and should be easy to merge. Later, if you have a maven artifact we can update the code to use it.

Cheers!

**Comment by eduramiba** [comment]
Hi Vincent,
Finally your plugin is merged and should be available soon. Thank you very much for the effort and the patience for this to be merged.

I made some small corrections to your code, so please be sure to merge the following pull request into your codebase so you can later update the plugin: https://github.com/vtraag/gephi-leiden-plugin/pull/1

**Comment by eduramiba** [comment]
Your plugin is now available at https://gephi.org/plugins/#/plugin/leiden-algorithm-gephi-plugin and in Gephi - Tools - Plugins menu

**Comment by vtraag** [comment]
Great! Thanks for merging it and making it available!

I'll be sure to merge any changes back in my fork.

**Comment by mbingenheimer** [comment]
The URL in the Plugin Manager Description:
Homepage: http://github.com/gephi/gephi-plugins/leiden-algorithm-gephi-plugin
does not seem to be correct.
Perhaps change to:
https://gephi.org/plugins/#/plugin/leiden-algorithm-gephi-plugin

**Comment by vtraag** [comment]
Thanks @mbingenheimer, I just moved your message to an issue in the gephi-leiden-plugin repository https://github.com/vtraag/gephi-leiden-plugin/issues/3.

@eduramiba, perhaps best to close the pull request? I've merged back the changes in my fork.

**Comment by eduramiba** [comment]
@vtraag Sure, what request? I think everything is correct and merged.

**Comment by vtraag** [comment]
Sorry, perhaps I misunderstood, I thought it was merged but not closed. I thought once the pull request was closed, it wouldn't be possible to comment on it any longer? But apparently it is?

**Comment by eduramiba** [comment]
Yeah I think comments can be added unless I block them

**Comment by vtraag** [comment]
OK, no problem, good to know, thanks!

**Pull request merged**
