### PR TITLE
Spatial Ranking comeback

### PR DESCRIPTION
**Pull request by mbastian**
## New plugin or plugin update?

* [ ] New Plugin
* [x] Update

## What is the purpose of this plugin?

Map attributes to X/Y/Z coordinates to create scatter plots.

Requested in #271 by @grandjeanmartin.

## How to test your plugin in Gephi?

1. Load any graph, preferably with some columns
2. Go to Appearance and notice the extra icon for coordinates
3. Select Ranking and the column you want to map to coordinates
4. Select the axis and the min/max size
5. Press Apply

Note that I also added a "Simple" transformer that does the same thing as the random layout.

## Checklist before submission

* [X] Did you merged with the `master` branch to get the latest updates?
* [X] Did you build and test the plugin successfully locally?
* [X] Did you include metadata (e.g. plugin author, license) in the `pom.xml` file
* [X] Did you make sure NOT to include any unecessary files in your PR?
* [X] Did you write unit tests to test your plugin functionalities? -> Yes added 2 basic tests

### CODE REVIEW

**Comment by mbastian** [comment]
@grandjeanmartin How would you suggest to rename this plugin? ;)

**Comment by grandjeanmartin** [comment]
@mbastian you rock! For the name, feel free to use the one that suits you, to me something like « network to scatter plot » would be the most descriptive.

**Comment by seinecle** [comment]
Indeed, I came here thinking of a plugin that would have to do with longitudes and latitudes, because of "spatial". Dropping " spatial" in the name could avoid that.

**Comment by mbastian** [comment]
Ok, I go with `Position Ranking` then as a good comprimise.

**Pull request closed without merging**
