### PR TITLE
BoundingDiameters

### PR DESCRIPTION
**Pull request by alexiooo**
We have written a gephi plugin implementing the BoundingDiameters algorithm for fast calculation of network diameter and radius. See the papers referenced in the README file for details on the algorithm.

### CODE REVIEW

**Comment by eduramiba** [comment]
Hi Alex,
Finally your plugin is merged and should be available soon. Thank you very much for the effort and the patience for this to be merged.

I made some small corrections to your code, so please be sure to merge the following pull request into your codebase so you can later update the plugin: alexiooo#1

**Comment by eduramiba** [comment]
Your plugin is now available at https://gephi.org/plugins and in Gephi - Tools - Plugins menu

**Comment by alexiooo** [comment]
Hey Eduardo,

We noticed some issues:
The link for the source from within Gephi leads to a 404 page, the correct link should be https://github.com/gephi/gephi-plugins/tree/bounding-diameters-plugin

The Gephi Marketplace only lists 'T. Oosterhoorn' as author, instead of all six of us (C. Deve, B. Honig, A. Keizer, S. Lin, D. Nieuwenhuizen, T. Oosterhoorn)

Can these be fixed or how would we fix them?

**Comment by eduramiba** [comment]
Hi Alex, I will correct it, I guess it's not handling multiple `author` tags correctly.

**Pull request merged**
