### PR TITLE
Plugin for new Merge Strategy

### PR DESCRIPTION
**Pull request by xgg3**
Hi everyone, 

We are developed a new feature for Data Laboratory Merge Strategies. 
It works like Open Office Calc Functions, which allow you to use formula to combine cells to obtain a result in another cell.

With the new Merge Strategy called "Apply Custom Formula", you can create a new column combining different Number Columns by a formula.

### CODE REVIEW

**Comment by eduramiba** [comment]
Thanks for the pull request! We will review it as soon as possible

**Comment by xgg3** [comment]
Hi @eduramiba !

We have also fixed a couple of bugs. We're not sure if those new changes done after pull request have been added. Do you?

If not, please reject this pull request and we'll do again.

**Comment by eduramiba** [comment]
@xgg3 Sorry, I still need to check this, thanks for fixing bugs!

**Comment by eduramiba** [comment]
Hi, thanks for the request! I fixed some problems in pull request https://github.com/oscarfont/gephi-plugins/pull/1 Please merge it so we can accept this.

**Comment by eduramiba** [comment]
Hi,
Finally your plugin is merged and should be available soon. Thank you very much for the effort and the patience for this to be merged.

I made some corrections to your code, so please be sure to merge the pull request into your codebase so you can later update the plugin.

**Comment by eduramiba** [comment]
Your plugin is now available at https://gephi.org/plugins and in Gephi - Tools - Plugins menu

**Pull request closed without merging**
