### PR TITLE
Twitter Streaming Importer 1.4.2

### PR DESCRIPTION
**Pull request by totetmatt**
TSI_142

* Add possibility to filter per language (Twitter API Feature) : https://developer.twitter.com/en/docs/tweets/filter-realtime/guides/basic-stream-parameters

* Add "Random Sample" that will use the sample Stream API (Twitter API Feature) :  https://developer.twitter.com/en/docs/labs/sampled-stream/overview

* Review  Save & Load filter configuration in json

### CODE REVIEW

**Comment by eduramiba** [comment]
Great! Thank you Matthieu :)

**Comment by eduramiba** [comment]
Sorry, the build is failing so I will upload this manually later.

**Comment by eduramiba** [comment]
I uploaded this manually, can you please try to install it in Gephi? Thanks again!

**Comment by andypiper** [comment]
Hi there, just to clarify, this plugin is using Twitter4J so I believe that the sample stream will be this one, rather than the newer one you referred to (the data format is also different on the newer sample stream, so you would need additional logic I suspect). https://developer.twitter.com/en/docs/tweets/sample-realtime/overview/get_statuses_sample

**Pull request merged**
