### PR TITLE
Adding a plugin for displaying attributes of a node on mouse hover

### PR DESCRIPTION
**Pull request by atopion**
Hi,
I have created this plugin, that produces an overlay displaying the nodes attributes on mouse hover.
It can be activated/deactivated under Tools -> Inspector or with the keyboard shortcut Ctrl + Alt + I.

While exploring large, unknown graphs, I find it cumbersome to constantly switch to the Data Laboratory to get information about a particular node. The node edit tool makes this easier, but it is unintuitve / hard to find without instructions and also displays the nodes "meta-information (color, position, label size, etc)" which distract from the important information about the node (while exploring).

I think this plugin would improve the user experience and provides a more intuitive way of exploring graphs.

I also think it could be a possible solution / improvement for issue [https://github.com/gephi/gephi/issues/459](https://github.com/gephi/gephi/issues/459)

Thank you for your time.

Screenshot:
gephi-inspector-screenshot

### CODE REVIEW

**Comment by eduramiba** [comment]
Great work, thanks! I will review it

**Comment by mbastian** [comment]
Hi @atopion  I would like to propose some changes to your PR in light of the recent Gephi upgrades. In this PR, could you enable my contributions please, via https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

Thanks!

**Comment by mbastian** [comment]
Hi @atopion and thanks for the submission. It's a neat idea that fills a gap we have in Gephi. I've reviewed it and made a few changes and improvements:
- Merged with `master` to get the latest changes
- Converted the plugin to a proper `Tool` using the `tools-api` as this was far more suitable than a top-level context menu. Let me know if you disagree :) 
- Change mouse location code to work with HighDPI screens (one has to use a global scale value)
- Sort columns so that properties appear first and then sorted by column index
- Use column title instead of ID

Let me know what you think. This is ready to be merged I think.

**Comment by atopion** [comment]
Hi @mbastian 
The changes look good to me.
It would be nice to have this finally merged.
Thanks for taking the time.

**Comment by mbastian** [comment]
Cool, I'll merge then. The icon is not amazing but should be fine for a first version. Feel free to update it if you want.

**Comment by mbastian** [comment]
@atopion Your inspector plugin is now available in Gephi (starting from version 0.9.3). I've also created a copy of your branch to this repository with the name `inspector-tool-plugin`. I've added you to a `Plugin Developers` Gephi Team so that you should have write access to this branch. We found that it makes updates easier when plugin developers directly work in this repository, as opposed to their fork.

**Comment by atopion** [comment]
@mbastian 
Great news. Thank you for your help.
Kind regards, atopion

**Pull request merged**
