### PR TITLE
Similaritycomputer

### PR DESCRIPTION
**Pull request by seinecle**
A series of commits following user feedback on Facebook.

### CODE REVIEW

**Comment by eduramiba** [comment]
Hi,
It seems this reverts my changes from https://github.com/seinecle/gephi-plugins/pull/4 ?

Also, a plugin should only change its own pom.xml and its own readme (modules/SimilarityComputer/README.md), instead of the repository readme, just for easy merging.

**Comment by seinecle** [comment]
I was surprised too. Don't know, I must have neglected to pull your branch before working on it - so actually I worked from a previous version. Oh that needs too much discipline. I am learning... Can you still merge?

**Comment by eduramiba** [comment]
It looks like you have a broken branch here again https://github.com/seinecle/gephi-plugins/tree/similaritycomputer (includes all modules)

You probably pulled from master-forge or something. You should reset your repository to this commit https://github.com/seinecle/gephi-plugins/commit/77da9c81ddba3a715d51c0627ef4f46133adff8a and then try to cherry-pick your commits from today or something... Or just redo the changes if they are not too many.

Git can be a bit tricky sometimes... (make a copy of your branch first)
Check http://stackoverflow.com/questions/5816688/resetting-remote-to-a-certain-commit

**Comment by seinecle** [comment]
I cloned the branch at the commit you indicated locally, added the commits I had made since, and then I did not know how to send this new version back to github. Deleted the similaritybranch on Github (WRONG), and pushed my local branch (I gave it the same name, similaritycomputer) to seinecle/gephi-plugins. But now the commit history is entirely different, can't make a pull request from this branch to gephi/gephi-plugins. Argh.

**Comment by eduramiba** [comment]
Mmm it looks like you created a new git repository and just copied the files instead of a hard reset to the commit you had. If you need it, I have a copy of your old branch at  https://github.com/eduramiba/gephi-plugins/commits/similaritycomputer

For your branch to be merged it has to origin from gephi-plugins/master.

**Pull request closed without merging**
