### PR TITLE
Force atlas 3 d

### PR DESCRIPTION
**Pull request by seinecle**
Migrated to 0.9

### CODE REVIEW

**Comment by eduramiba** [comment]
Hi,
You should remove from git all the files in `ForceAtlas3D` directory in the repository root.

Also you can move the plugin image to the `modules/ForceAtlas3D/src/img` directory like other plugins

**Comment by yaceben** [comment]
Any update on this ? It would be very helpful to be able to use it...

**Comment by eduramiba** [comment]
We could merge this, though would it be useful given that Gephi no longer supports 3d?

**Comment by yaceben** [comment]
If it is possible to rotate the view of the graph on a third axis I believe that it would still be very useful even if it only renders circles instead of spheres.

Cheers

**Comment by cfdv** [comment]
Force atlas 3d is the best. Please merge!

**Comment by DiegoUrbinaLum** [comment]
Has anyone been able to use it? I am having trouble with 2 other plugins:
1. org_gephi.data.attributes.api
2. org_gephi.dynamic.api

Does anyone know the way to solve this issue? I'm using Gephi 0.9.1

Thanks in advance.

**Comment by ParkhaeShin** [comment]
> Has anyone been able to use it? I am having trouble with 2 other plugins:
> 
> 1. org_gephi.data.attributes.api
> 2. org_gephi.dynamic.api
> 
> Does anyone know the way to solve this issue? I'm using Gephi 0.9.1
> 
> Thanks in advance.

Yeah i also have that problem too

**Comment by brienna** [comment]
Hoping that this gets merged 🤞🏻

**Comment by mbastian** [comment]
I updated the plugin to the latest updates and merged. It's available in Gephi and https://gephi.org/plugins/#/plugin/force-atlas-3d

**Pull request merged**
