### PR TITLE
Migrated Give color to edges to 0.9.1

### PR DESCRIPTION
**Pull request by seinecle**
Just like "Give color to nodes", but for edges.

### CODE REVIEW

**Comment by eduramiba** [comment]
Sorry for the delay, I created a pull request on your branch so we can finally merge this :)

**Comment by eduramiba** [comment]
Hi Clement, can you merge the PR in your branch please?

Thanks!

**Comment by seinecle** [comment]
Hi, sorry I am so unfamiliar with github, and time has passed since the last time I used this kind of stuff. Can you help me and tell me how to do it? From Netbeans or else?

**Comment by eduramiba** [comment]
Sure, just click on the merge pull request button of the 3 pull requests at https://github.com/seinecle/gephi-plugins/pulls

**Comment by eduramiba** [comment]
Hi, did you find the button? Thanks

**Comment by seinecle** [comment]
sorry I had not seen your email... now fixed! Thanks a ton!

**Comment by eduramiba** [comment]
Awesome, thanks! I will merge these 2 shortly

**Comment by eduramiba** [comment]
Your plugin is now available at the update center :smiley:

**Comment by seinecle** [comment]
wowow

**Pull request merged**
