### PR TITLE
Map of countries branch

### PR DESCRIPTION
**Pull request by seinecle**
Added an edge attribute to the map, to make it possible to filter out just the edges of the map, without touching the network.
-> in response to this issue: https://github.com/seinecle/Plugins-for-Gephi/issues/30

### CODE REVIEW

**Comment by eduramiba** [comment]
Merged, will publish changes shortly.

**Comment by eduramiba** [comment]
Actually, I noticed this plugin uses

```xml
<groupId>net</groupId>
<artifactId>clementlevallois</artifactId>
```

Could you change it to this (or similar) please?

```xml
<groupId>net.clementlevallois</groupId>
<artifactId>mapofcountries</artifactId>
```

**Comment by seinecle** [comment]
So you just did it yourself it seems?

**Comment by eduramiba** [comment]
No, I think you will need to create a new pull request since this is already merged.

**Pull request merged**
