### PR TITLE
MultiGravity ForceAtlas2

### PR DESCRIPTION
**Pull request by suryanash**
I made a modification of ForceAtlas2 using multiple sources of gravity. Graphs are expected to have an attribute which is "gravity_x" and "gravity_y" which need to be doubles, that give approximate locations of sources of gravity. The distance between the sources of gravity can be modified using the parameters for the layout. The main benefit of this algorithm is that graphs can be coerced into certain shapes based on some data related to the data set.

### CODE REVIEW

**Comment by eduramiba** [comment]
Sounds cool! Could you please add some sample images to your plugin? See https://github.com/gephi/gephi-plugins/tree/geolayout-plugin/modules/GeoLayout/src/img for example

**Comment by suryanash** [comment]
Have now added some images of the modification in use. I have also added images of what the layouts looked like using just FA2, to compare to how they look with MGFA2.

**Comment by suryanash** [comment]
I have removed the previous images and added ones that I believe demonstrate the use of this layout better.

**Comment by eduramiba** [comment]
Hi,
I created a pull request in your branch that fixes some parts of the code. Please accept it so we can merge this.

**Comment by eduramiba** [comment]
Merged in commit d4a43cbb4a390f35ac923f68b7666b624b041eac

**Comment by eduramiba** [comment]
Your plugin is now available at the update center :smiley:

**Pull request closed without merging**
