### PR TITLE
SHP Export: Migrated to 9.1

### PR DESCRIPTION
**Pull request by romanseidl**
I finally migrated the plugin to 9.1 and updated the Geotools dependencies to gt17.

The plugin depends on the osgeo-repo, I hope that's OK.

I hope this pull request is now OK, I am not so sure...

### CODE REVIEW

**Comment by eduramiba** [comment]
Thanks for the pull request! I will check it as soon as possible

**Comment by romanseidl** [comment]
Thx! Just a short question: I wanted to send this to someone for testing. Is there a way to create a nbm or something similar somebody can install? I though "mvn package" would do so but I couldn't find a package afterwards.

**Comment by eduramiba** [comment]
I think you need to enable release profile with ```-P release```

**Comment by romanseidl** [comment]
I managed to produce it, I think it was

     mvn nbm:nbm

Anyway, the colleague who tested it had no problems whatsoever.

**Comment by eduramiba** [comment]
https://github.com/romanseidl/gephi-plugins/pull/1 pending to merge this

**Comment by eduramiba** [comment]
Hi, were you able to merge the PR?

**Comment by eduramiba** [comment]
Please merge https://github.com/romanseidl/gephi-plugins/pull/1

**Pull request merged**
