### PR TITLE
changed artifact id

### PR DESCRIPTION
**Pull request by seinecle**

### CODE REVIEW

**Comment by eduramiba** [comment]
Oops it seems you added many other files. This should only change the pom.xml file

**Comment by seinecle** [comment]
Yes I don't now why, pulling from seinecle/gephi-plugins, it pulled all the plugins not just map-of-countries :/ So when I pushed back a number of other files where attached. A bit los there.

**Comment by seinecle** [comment]
Did I fix the pull request? Or not?

**Comment by eduramiba** [comment]
It seems I merged my own branch the first time https://github.com/gephi/gephi-plugins/pull/93

You could work on that (would need to merge new commits from the new feature) or other option is that you work on master-forge for this. First option is better for future work in this plugin.

**Comment by eduramiba** [comment]
If it's a bit of a git mess I can do it tomorrow and you just copy my branch.

**Comment by seinecle** [comment]
ok!

**Comment by eduramiba** [comment]
Closing in favor of #146
You can just replace your branch with mine: https://github.com/eduramiba/gephi-plugins/tree/mapOfCountriesBranch

**Pull request closed without merging**
