### PR TITLE
Twitter Stream Importer 1.3.0 : Emoji Network

### PR DESCRIPTION
**Pull request by totetmatt**

### CODE REVIEW

**Comment by eduramiba** [comment]
Thanks for the request! I expect to merge it this weekend.

**Comment by totetmatt** [comment]
Don't worry, no need to rush for this ;-)

**Comment by eduramiba** [comment]
Merged, awesome! I just changed the Manifest-Version to 1.0 as it should never change, it's the version of the manifest file type.

**Comment by eduramiba** [comment]
The new version should be available soon

**Pull request merged**
