### PR TITLE
Pull request for plugin "Excel / Csv Importer" migrated to 0.9.1

### PR DESCRIPTION
**Pull request by seinecle**
The code for this plugin is ugly, sorry, it reflects older times.

### CODE REVIEW

**Comment by NDuma** [comment]
Cross reffing:
github.com/seinecle/Plugins-for-Gephi/issues/26

**Comment by WouterSpekkink** [comment]
I can imagine that the Gephi team is very busy, but I am wondering when the open pull requests are going to be dealt with. I would like to be able to use the excel/csv-importer again, as well as some of the plugins that I wrote myself. Some of them have been open pull requests for quite some time now.

**Comment by eduramiba** [comment]
Hi, sorry for the delay.

This is the first pull request that I will merge of all pending. Unfortunately my time for this is very limited at the moment.

**Comment by WouterSpekkink** [comment]
No problem. As I said, I understand that you guys must be very busy with other stuff as well. Of course I am in the first place very grateful for all the amazing work that you have already done. I was just checking. :)

**Comment by eduramiba** [comment]
Hi, finally this is merged (on the master-forge branch, plugin pull requests should go there) and available in plugins center!

I had to apply multiple fixes to the code and remove unnecessary files and duplicated resources.
So please overwrite your branch at https://github.com/seinecle/gephi-plugins/tree/ExcelCsvImporter with the new code at https://github.com/gephi/gephi-plugins/tree/master-forge/modules/ExcelCsvImporter so it can be tracked later.

A general refactor would be good anyway, but it works :)

**Comment by eduramiba** [comment]
The 0.8.2 version has a different readme. Can you review that? We can update the new one to include the instructions and maybe merge them.

New: https://gephi.org/plugins/#/plugin/excelcsvimporter
Old: https://gephi.org/plugins/#/plugin/excel-csv-converter-to-network

**Pull request closed without merging**
