### PR TITLE
Groups by partition plugin

### PR DESCRIPTION
**Pull request by sergipuig**
A plugin which creates a graph where each node is the aggregation of a group of nodes (of the previous workspace using the colors given to the nodes).

### CODE REVIEW

**Comment by joancf** [comment]
Hi, you should solve the conflicts, 
and do a new pull request

**Comment by eduramiba** [comment]
Thanks for the pull request, will review when possible!
It's not necessary for you to fix the conflicts, I usually do it manually when merging plugins, no problem.

**Comment by joancf** [comment]
Hi Eduardo, @eduramiba  Do you think it will be available soon on Gephi 0.9.2?

**Comment by eduramiba** [comment]
Hi Joan, I have been really busy lately, but I will try my best to get the plugin out in november.
Thanks for your patience.

**Comment by joancf** [comment]
Don't worry, I'm teaching at the university and some the pull requests were done by some computer science students I got in June. But now I'm teaching another course on SNA, to marketing students,  and i was wondering if it could be possible to have to have these improvements before ending the course, so they can use it. 
This one is very useful to visualize the output of the Modularity algorithm in order to show the relationships between groups, others (like the columns calculator) can be used to compute some metrics like effective size of each user...  but we end the course  soon (6th December) and I think is a bit difficult that you can upload it, I test it and rewrite some of the exercises for this course.

**Comment by eduramiba** [comment]
Hi, thanks for the request! I fixed some problems in pull request sergipuig#3 Please merge it so we can accept this.

**Comment by eduramiba** [comment]
Hi,
Finally your plugin is merged and should be available soon. Thank you very much for the effort and the patience for this to be merged.

I made some corrections to your code, so please be sure to merge the pull request into your codebase so you can later update the plugin.

**Comment by eduramiba** [comment]
Your plugin is now available at https://gephi.org/plugins and in Gephi - Tools - Plugins menu

**Comment by joancf** [comment]
Great!

**Pull request merged**
