### PR TITLE
Addition of Circle Pack layout plugin for grouping nodes

### PR DESCRIPTION
**Pull request by pflans**
This is a new plugin for creating circle pack layouts in Gephi using Mike Bostock's implementation in [d3-hierarchy](https://github.com/d3/d3-hierarchy/) but ported over to Java. Multiple levels of hierarchy can be used to create deeper circle packs.

This is my first attempt at a Gephi plugin, critique is welcome.

### CODE REVIEW

**Comment by eduramiba** [comment]
Awesome, thanks for the request! I will check it as soon as possible.
For now, please update the sourceCodeUrl part of the pom with the correct value, as our plugin does not fill it correctly.

**Comment by eduramiba** [comment]
Hi,
I created a pull request with fixes and improvements: https://github.com/sasakiassociates/gephi-plugins/pull/1
Please merge it first to your branch and your master before we can merge this.

**Comment by pflans** [comment]
I've merged in your changes to /master and /circlePack branches. Thanks for your improvements.

**Comment by eduramiba** [comment]
Merged, thanks! Your plugin will be available soon

**Comment by eduramiba** [comment]
Your plugin is now available

**Pull request merged**
