### PR TITLE
Add KatzCentrality plugin.

### PR DESCRIPTION
**Pull request by yossisp**
The plugin adds [Katz Centrality](https://en.wikipedia.org/wiki/Katz_centrality) calculation in Statistics module.

### CODE REVIEW

**Comment by mbastian** [comment]
Hi @yossisp I would like to propose some changes to your PR in light of the recent Gephi upgrades. In this PR, could you enable my contributions please, via https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

Thank you!

**Comment by yossisp** [comment]
> Hi @yossisp I would like to propose some changes to your PR in light of the recent Gephi upgrades. In this PR, could you enable my contributions please, via https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork
> 
> Thank you!

Hi @mbastian, sure no problem, I see that "Allow edits by maintainer" checkbox is checked, please let me know if you have any issues adding your commits.

**Comment by mbastian** [comment]
Thanks @yossisp! Unfortunately it seems that your branch is a fork from `master-forge` instead of `master`. Normally there should only be your module in there. Therefore I created a new branch with your code directly on this repository at `https://github.com/gephi/gephi-plugins/tree/katz-centrality-plugin`. I've made some updates to make the plugin work for the recent Gephi version. You can check it out and see if it works fine for you too.

**Comment by mbastian** [comment]
Ah also, I don't know if you had a chance to look at the alternative implementation on this other PR: https://github.com/gephi/gephi-plugins/pull/186

Your implementation relies on Matrices while this other doesn't. I'm afraid matrices would take a lot of memory but it might be faster.

**Comment by yossisp** [comment]
> Thanks @yossisp! Unfortunately it seems that your branch is a fork from `master-forge` instead of `master`. Normally there should only be your module in there. Therefore I created a [new branch ](https://github.com/gephi/gephi-plugins/tree/katz-centrality-plugin) with your code directly on this repository. I've made some updates to make the plugin work for the recent Gephi version. You can check it out and see if it works fine for you too.

Thanks @mbastian ! I used the katz centrality nbm file from the branch you created and it seems fine, but I also want to check with the university I developed the plugin for that they also confirm everything works as expected. Will update you as soon as I get their feedback. The only thing is that I get an error when running the plugin via `mvn org.gephi:gephi-maven-plugin:run` same error as described [here](https://github.com/gephi/gephi/issues/1059) I also use Mac. It happened now that I have to use JDK 11 for Gephi.

**Comment by yossisp** [comment]
> #186



> Ah also, I don't know if you had a chance to look at the alternative implementation on this other PR: #186
> 
> Your implementation relies on Matrices while this other doesn't. I'm afraid matrices would take a lot of memory but it might be faster.

I remember I saw this [pr](https://github.com/gephi/gephi-plugins/pull/186) however I'm not sure it even works. Its author didn't respond since 2019. As far as I know the plugin I developed is used by the university which ordered this development and is not causing any memory issues.

**Comment by mbastian** [comment]
Thanks @yossisp I merged manually from the `katz-centrality-plugin` branch. Your plugin is now published officially: https://gephi.org/plugins/#/plugin/katz-centrality. 

If you want to make some changes, you can do that directly from that branch instead of your fork.

**Comment by yossisp** [comment]
> Thanks @yossisp I merged manually from the `katz-centrality-plugin` branch. Your plugin is now published officially: https://gephi.org/plugins/#/plugin/katz-centrality.
> 
> If you want to make some changes, you can do that directly from that branch instead of your fork.

@mbastian  Thanks for publishing! I have a few questions:

1. Was the code merged to master branch? I don't see it in the master branch of gephi-plugins repo. I also see that the branch is [8 commits ahead of master](https://github.com/gephi/gephi-plugins/compare/master...katz-centrality-plugin).
2. When I go to the plugin [page](https://gephi.org/plugins/#/plugin/katz-centrality) and click on the "Source code" I get "File not found" error.
3. The images in the plugin [page](https://gephi.org/plugins/#/plugin/katz-centrality) are broken can they be fixed?

**Comment by mbastian** [comment]
> @mbastian Thanks for publishing! I have a few questions:
> 
> 1. Was the code merged to master branch? I don't see it in the master branch of gephi-plugins repo. I also see that the branch is [8 commits ahead of master](https://github.com/gephi/gephi-plugins/compare/master...katz-centrality-plugin).

The `master` branch is the template branch for new plugins but the `master-forge` branch is actually where all the plugins are merged. So one needs to compare to this branch.

> 2. When I go to the plugin [page](https://gephi.org/plugins/#/plugin/katz-centrality) and click on the "Source code" I get "File not found" error.

Yes, you can fix this by changing this [line](https://github.com/gephi/gephi-plugins/blob/d321a3fcd96625bcbb45469208bd59f3802fa6f3/modules/KatzCentrality/pom.xml#L72). Make sure to also increment your plugin version otherwise changes are not taken in account.

> 3. The images in the plugin [page](https://gephi.org/plugins/#/plugin/katz-centrality) are broken can they be fixed?

You use relative paths in your [README](https://raw.githubusercontent.com/gephi/gephi-plugins/katz-centrality-plugin/modules/KatzCentrality/README.md). Change that to absolute paths and it should work.

**Pull request closed without merging**
