### PR TITLE
Agensgraph Plugin

### PR DESCRIPTION
**Pull request by dehowef**
Plugin for importing graph data from AgensGraph Database, a graph database based on PostgreSQL.

### CODE REVIEW

**Comment by eduramiba** [comment]
Hi, thanks for the pull request. I will check this soon.

Meanwhile, I will need that you remove the entire .idea folder from the pull request, and also restore the nbactions.xml file, which seems to have been removed.

**Comment by dehowef** [comment]
Hey Eduardo,
Thanks for responding! I just removed the .idea folder and restored the nbactions.
-Dehowe

**Comment by eduramiba** [comment]
Hi,
Sorry I have not been able to review this completely yet, but you should never merge your plugin branch with master-forge. Please reset your branch to commit https://github.com/gephi/gephi-plugins/pull/155/commits/9929a2853c08a6ce278100062807257b2003ca8d

**Comment by dehowef** [comment]
Hi Eduardo,
Woops! My mistake. I just amended those changes.

**Comment by eduramiba** [comment]
I created a pull request in your branch to be merged before accepting this https://github.com/bitnine-oss/gephi-plugins/pull/1

**Comment by eduramiba** [comment]
Great, I will merge this soon. Can you undo the merge with master forge again though?

**Comment by eduramiba** [comment]
Bump :)

**Comment by eduramiba** [comment]
I think I can merge it not including the latest merge master forge commit but please remove it for future updates of this plugin with pull requests.

**Comment by eduramiba** [comment]
I merged this pull request up to the merge commit with my changes. Your plugin will be available soon.
Please remote the merge with master-forge anyway, for future changes of your plugin. Plugin branches should never merge with master-forge.

**Comment by eduramiba** [comment]
Merged at 520ef4aaa18d9b4b79955b42bd7b14da098ed521

**Comment by eduramiba** [comment]
Your plugin is now available :)

**Comment by dehowef** [comment]
Hey @eduramiba,
Sorry for the late response. It's been pretty hectic on my end. Thank you for your support through the process!

-Dehowe

**Pull request closed without merging**
