### PR TITLE
Mds metric

### PR DESCRIPTION
**Pull request by WouterSpekkink**
I reopened the pull request, after resolving an issue I had with including the mdsj.jar, on which the plugin depends. To build the plugin locally, the mdsj.jar needs to be added to the local maven repository of the builder to prevent unresolved dependencies. I am not sure how to otherwise make sure that the dependency is resolved. I used the accepted solution mentioned here to resolve the dependency issue: http://stackoverflow.com/questions/4955635/how-to-add-local-jar-files-in-maven-project

### CODE REVIEW

**Comment by eduramiba** [comment]
Where does the mds.jar come from? Is it available in maven central?

If it's not, maybe we can upload it where we store thirdparty libraries: https://github.com/gephi/gephi/tree/mvn-thirdparty-repo but we should avoid uploading jars to master-forge branch.

**Comment by WouterSpekkink** [comment]
Hi Eduardo,

I expect it is not in maven central. It was created a while ago by two
scholars from an Austrian institute, and they uploaded it to a dedicated
website. Can I upload it to the third-party repo, or do you prefer to do
that yourself?

Best,

Wouter

2016-09-21 15:34 GMT+01:00 Eduardo Ramos <notifications@github.com>:

**Comment by eduramiba** [comment]
Is the source code available? What's the license?

**Comment by WouterSpekkink** [comment]
I am not sure if the source code itself is available. It is released with a
Creative Commons License.

This is the website: http://algo.uni-konstanz.de/software/mdsj/

2016-09-21 15:47 GMT+01:00 Eduardo Ramos <notifications@github.com>:

**Comment by WouterSpekkink** [comment]
Hmm, giving this another look makes me realise I should make more explicit
that the plugin should not be used for commercial purposes, right?

2016-09-21 15:49 GMT+01:00 Wouter Spekkink <wouterspekkink@gmail.com>:

**Comment by eduramiba** [comment]
Yeah, I guess the plugin should contain the citation to the mds library, and the no commercial use thing.
Also, it would be nice to have the Citation in the Gephi UI, like statistics algorithms do.

You can also contact the author just to make sure it's ok to upload the jar in https://github.com/gephi/gephi/tree/mvn-thirdparty-repo

**Comment by WouterSpekkink** [comment]
Hi Eduardo,

I will make some changes somewhere in the coming days (not sure when I will
have the time). The reference is already included in the UI (I indeed took
the other statistics modules as an example), and I report in every online
description of the plugin. However, I still need to add something about the
commercial-use stuff, because I feel that is not sufficiently clear.

I will contact the authors of the plugin as well. I will send you a message
once I have made all the necessary changes.

Thanks.

Best,

Wouter

2016-09-26 9:26 GMT+01:00 Eduardo Ramos <notifications@github.com>:

**Comment by eduramiba** [comment]
Great, thanks!

**Comment by WouterSpekkink** [comment]
Both authors of the plugin (Christian Pich and Ulrik Brand) are okay with
us uploading the MDSJ library to the repository. I will make some small
changes to the plugin soon to highlight the license's conditions of use,
and then I think I will be ready for another pull request.

2016-09-26 9:49 GMT+01:00 Eduardo Ramos <notifications@github.com>:

**Comment by eduramiba** [comment]
Cool! You can just update this one by pushing more commits to your branch.

**Comment by WouterSpekkink** [comment]
Hey Eduardo,

I took at look at the third party repo:
https://github.com/gephi/gephi/tree/mvn-thirdparty-repo

I am not sure to properly add the MDSJ libary to it. Could you give me some
advice?

Best,

Wouter

2016-09-27 9:21 GMT+01:00 Eduardo Ramos <notifications@github.com>:

**Comment by eduramiba** [comment]
Hi Wouter,
Soon I will create the artifact and upload it so you can use it.

**Comment by WouterSpekkink** [comment]
Great, thanks. I guess I just have to point to a certain address in the pom
file right? I already made most other changes. Also cleaned up some things
in the code.

2016-10-03 13:20 GMT+01:00 Eduardo Ramos <notifications@github.com>:

**Comment by eduramiba** [comment]
I uploaded the artifact `uni-konstanz.de.algo:mdsj` at https://github.com/gephi/gephi/blob/mvn-thirdparty-repo/uni-konstanz/de/algo/mdsj/0.2

You will probably need to add the thirdparty repository as in https://github.com/gephi/gephi/blob/master/pom.xml

**Comment by WouterSpekkink** [comment]
Hey Eduardo,

I made a new commit. It took my a while, because I had some issues trying to create the dependency, but I think I worked it out in the end. Small summary:
- added third-party repo to repositories (in the pom-file)
- added mdsj as a dependency
- added info to plugin dialogue about terms of use (creative commons license)
- made some code style improvements and removed comments that were personal reminders
- found an issue that causes gephi to get stuck if the plugin is run on an empty graph and fixed it
- added an image, because I saw you did that with my other plugins as well

I think that is about it. I hope I got the code style right this time.

Best,

Wouter

**Comment by eduramiba** [comment]
Great, I will review the code as soon as possible and if necessary ask for additional changes.

**Comment by eduramiba** [comment]
Hi,
I created a pull request in your branch that fixes some parts of the code. Please accept it so we can merge this.

Also, I don't really understand the algorithm so I will assume it's correct :laughing:

**Comment by WouterSpekkink** [comment]
Hi Eduardo,

Just a check to be sure. It seems like a lot of code was removed, including
the code that adds and removes columns to the data laboratory based on the
settings of the user. It also seems that nothing came in their place. Won't
this break the plugin, or am I overlooking something?

Best,

Wouter

2016-10-03 19:37 GMT+01:00 Eduardo Ramos <notifications@github.com>:

**Comment by WouterSpekkink** [comment]
Oh, right. Yes, I was overlooking something. I see that you condensed a few
hundred lines of code in only a dozen. Nice. :)

2016-10-03 21:43 GMT+01:00 Wouter Spekkink <wouterspekkink@gmail.com>:

**Comment by eduramiba** [comment]
Hi, I replaced those long parts with two for loops, as they were very
repetitive. The plugin runs the same but you can try it before merging.

**Comment by WouterSpekkink** [comment]
Looks much better, thanks. Perhaps the part of the algorithm that you were
wondering about is the part with the minValue, maxVaue stuff? That is just
used when the user uses edges that represent distances or similarities. To
handle them correctly, I needed to normalize them, and all that stuff is
basically an implementation of a commonly used normalization formula.

Thanks for all your work. Must be a pain to go through all that code.

2016-10-03 21:45 GMT+01:00 Eduardo Ramos <notifications@github.com>:

**Comment by eduramiba** [comment]
Merged in commit 3231f8518b7b4e97856eef614623ff1dc4e92e97

**Comment by eduramiba** [comment]
Your plugin is now available at the update center :smiley:

**Pull request closed without merging**
