### PR TITLE
changed some class names to avoid collision with other plugins.

### PR DESCRIPTION
**Pull request by seinecle**
tested when installed with the Excel/Csv importer plugin, runs fine now.

removed a System.out.println, too.

### CODE REVIEW

**Comment by eduramiba** [comment]
Hi,
Can you push a new commit to increase the plugin version?

**Comment by seinecle** [comment]
damn forgot that. Doing it now.

**Comment by eduramiba** [comment]
The update is now available

**Comment by seinecle** [comment]
Fantastic. Thanks a lot.

**Pull request merged**
