### PR TITLE
ExportToEarth Plugin

### PR DESCRIPTION
**Pull request by shepdl**
ExportToEarth upgraded to be compatible with Gephi 0.9.

### CODE REVIEW

**Comment by eduramiba** [comment]
Hi Dave,
If fixed several problems in your code, mostly about column types and column selection.

Please review and pull the changes in your branch from here https://github.com/eduramiba/gephi-plugins/tree/export-to-earth before we can merge this request.

**Comment by eduramiba** [comment]
Hi Dave,
Thanks, the plugin is now merged and will be available later (now Netbeans maven repository is down and the build fails).

I also removed some unused code in IconRenderer class, and its unnecessary dependencies to preview.

**Comment by eduramiba** [comment]
Hi,
Your plugin should be available now in Gephi update center. Please check everything is fine.
Congrats!

**Comment by eduramiba** [comment]
Hi Dave,
Your plugin was not being downloaded correctly by Gephi due to a problem in your pom (innecessary and incorrect nbm-maven-plugin version). See #105 

This has been fixed with commit https://github.com/gephi/gephi-plugins/commit/7422759f9431805711b5e9cce315745f79658405

Please include the changes in your branch

**Comment by shepdl** [comment]
Oops. Thank you! That's been fixed in my branch as well.

**Pull request merged**
