### PR TITLE
Hairball Buster Plugin

### PR DESCRIPTION
**Pull request by cmatties**

### CODE REVIEW

**Comment by cmatties** [comment]
Plugin that implements the Hairball Buster graph triage method described in DOI: 10.21307/connections-2019-009.

**Comment by eduramiba** [comment]
Hi, I migrated this source code to https://github.com/gephi/gephi-plugins/tree/hairball-buster-plugin since the module of a new plugin has to be added to master branch for working on it, and only then merged to master-forge.

Note to self: need Maven 3.3.9 and Java 8 to build plugins in master-forge. Will update in the future to work with new tooling when we have a new gephi release.

**Comment by eduramiba** [comment]
I will manually merge this to master forge now and try make a release.

**Comment by eduramiba** [comment]
Oh sorry for the long wait!

**Comment by eduramiba** [comment]
Hi,

The plugin is now downloadable from Gephi desktop and https://gephi.org/plugins/#/plugin/hairball-buster

Please test that everything works as expected.

Thanks for your plugin!!

**Pull request closed without merging**
