### PR TITLE
Oracle Database Driver

### PR DESCRIPTION
**Pull request by sturton**
Add Oracle Database Driver using existing Oracle client or Instant Client installation.

### CODE REVIEW

**Comment by eduramiba** [comment]
Sorry for the delay, I created a pull request on your branch so we can finally merge this :)

**Comment by sturton** [comment]
Okay

**Comment by eduramiba** [comment]
Can you merge it before please?

**Comment by sturton** [comment]
Can you walk me through the steps that you want to perform?

**Comment by eduramiba** [comment]
Sure, just click on the 'Merge pull request button' at https://github.com/sturton/gephi-plugins/pull/1

**Comment by WouterSpekkink** [comment]
Just chipping in here: I think it is a matter of going to your own branch of the repository, and you'll find a new pull request there (created by Eduardo). You can see the changes that Eduardo made and then merge the pull request. I just merged without going through the changes in detail.

**Comment by sturton** [comment]
Merged.

**Comment by eduramiba** [comment]
Your plugin is now available at the update center :smiley:

**Pull request merged**
